version: "3"
services:
    rabbitmq:
        image: rabbitmq
        hostname: rabbitmq
        restart: always
        ports:
            - "5680:5672" 

    consumer:
        build: consumer
        links:
            - rabbitmq
        command: python consumer.py

    producer:
        build: producer
        links:
            - rabbitmq
        command: python producer.py
